# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
plugins:          [jekyll-paginate]

# Setup
title:            Humor
tagline:          'Comedy'
description:      'This website argues how humor seldom changes due to the longevity of human experience. As the format of comedy evolves, notice how the culture at each time period has one consistent variable: making people happy.'
url:              http://actamu.github.io
baseurl:          /laughing-aggies/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

gems:
- jemoji

# Custom vars
# version:          2.2.0

github:
  repo:           https://github.com/actamu/laughing-aggies/
