# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
plugins:          [jekyll-paginate]

# Setup
title:            Humor
tagline:          'Evolution of Comedy'
description:      'This website argues how humor seldom changes due to the longevity of human experience. As the format of comedy evolves, notice how the culture of the time is reflected while one variable is consistent: making people happy.'
url:              http://actamu.github.io
baseurl:          /laughing-aggies/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.2.0

github:
  repo:           https://github.com/actamu/laughing-aggies/
