# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
plugins:          [jekyll-paginate]

# Setup
title:            Humor
tagline:          'Evolution of Comedy'
description:      'This website argues how the content of humor seldom changes due to a longevity of human experience. However, the format evolving reflects the culture of that time while keeping one common variable: making people laugh and happy.'
url:              http://actamu.github.io
baseurl:          /laughing-aggies/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.2.0

github:
  repo:           https://github.com/actamu/laughing-aggies/
