# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Humor
tagline:          'Evolution of Comedy'
description:      'The core argument of this website is to target high school and college demographics to show how the content of humor seldom changes due to a longevity of human experience. However, the format evolving reflects the culture. Additionally, the common variable across all forms of humor is the end goal: to make people laugh and leave them happy.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.2.0

github:
  repo:           https://github.com/poole/hyde
